Update Get-Commands.md
Streamerbot/docs pull request #24
Opened 2023-12-13 07:39 UTC by lebluxtv

added /me to messages in the code example to keep the same formatting as the example above ( without code )

2023-12-13 08:53 UTC, Ik1497 reviewed
I think it should probably be changed to CPH.SendAction instead, so when you use the YouTube one it won't give the twitch bit at the front
![image](https://github.com/Streamerbot/docs/assets/113038466/9b03986a-06a4-4bb1-815d-056f4487379a)

2023-12-14 02:07 UTC, GoWMan813 commented on streamerbot/3.api/1.sub-actions/core/commands/Get-Commands.md
> +        string message = "/me Commands Avaliable to you: ";
Should remove the /me

2023-12-14 02:08 UTC, GoWMan813 commented on streamerbot/3.api/1.sub-actions/core/commands/Get-Commands.md
>                  CPH.SendMessage(message, bot); // This will need to be changed to CPH.SendYouTubeMessage(message, bot); if you wish to send the message to Youtube
Should be CPH.SendAction for Twitch.

2023-12-14 02:08 UTC, GoWMan813 commented on streamerbot/3.api/1.sub-actions/core/commands/Get-Commands.md
> +                message = "/me Addional Commands for you: ";
Should remove the /me.

2023-12-14 02:10 UTC, GoWMan813 requested changes
Slash commands should not be part of docs as slash commands have been deprecated.  While Twitch does still allow use of /me it is highly advisable to use supplied CPH.SendAction Method to not confuse users of slash command abilities.

2023-12-14 02:18 UTC, GoWMan813 commented on streamerbot/3.api/1.sub-actions/core/commands/Get-Commands.md
>  - [<i class="mdi mdi-chevron-left"></i> **Commands Sub-Actions Reference *Go Back***](/Sub-Actions/Commands)
This whole section can be removed as well.  Artifacts left over from the old wiki system.
[<i class="mdi mdi-chevron-left"></i> **Commands Sub-Actions Reference *Go Back***](/Sub-Actions/Commands)
{.btn-grid .my-5}

2023-12-14 22:06 UTC, closed without merging